

#ifndef RESOURCESID_H_
#define RESOURCESID_H_
//resource type
#include "Manager/ResourcesNameRole.h"

/*
 * 게임에 사용되는 이미지 아이디들
 */
enum idImages{
	//common
	IMAGE_BACKGROUND = TYPE_IMAGE + SCENE_COMMON + STAGE_NONE + 1,
	IMAGE_MAIN_BACKGROUND,
	IMAGE_BACKGROUND_TABLE,
	//mainmenu
	IMAGE_VERTICALLY_START_BUTTON = TYPE_IMAGE + SCENE_MAINMENU + STAGE_NONE + 1,/////////////
	IMAGE_VERTICALLY_TUTORIAL_BUTTON,/////////////
	IMAGE_TITLE,
	//tutorial
	IMAGE_TUTORIAL = TYPE_IMAGE + SCENE_TUTORIAL + STAGE_NONE + 1,
	IMAGE_BACK_BOUTTON,
	//gameplay - gameplay
	IMAGE_HAND = TYPE_IMAGE + SCENE_GAMEPLAY + STAGE_GAMEPLAY + 1,
	IMAGE_BLOCK,
	IMAGE_ACCURACY,
	IMAGE_SCORE,
	IMAGE_SCORENUMBER,
	IMAGE_TIMEBAR,
	//gameplay - gameover
	IMAGE_GAMEOVER = TYPE_IMAGE + SCENE_GAMEPLAY + STAGE_GAMEOVER + 1,
	//gameresult
	IMAGE_HORIZONTAL_BUTTON = TYPE_IMAGE + SCENE_GAMERESULT + STAGE_NONE + 1,
	IMAGE_RESULT_WINDOW,
	//gameresult Now Info
	LABLE_NAME,
	LABLE_BLOCKS,
	LABLE_SCORE,
	//gameresult rank name;
	LABLE_FIRST_NAME,
	LABLE_SECOND_NAME,
	LABLE_THIRD_NAME,
	LABLE_FOURTH_NAME,
	LABLE_FIFTH_NAME,
	//gameresult rank block;
	LABLE_FIRST_BLOCKS,
	LABLE_SECOND_BLOCKS,
	LABLE_THIRD_BLOCKS,
	LABLE_FOURTH_BLOCKS,
	LABLE_FIFTH_BLOCKS,
	//gameresult rank score;
	LABLE_FIRST_SCORE,
	LABLE_SECOND_SCORE,
	LABLE_THIRD_SCORE,
	LABLE_FOURTH_SCORE,
	LABLE_FIFTH_SCORE,

};

/*
 * 게임에 사용되는 사운드 아이디들
 */
enum idSounds{
	//common
	SOUND_CLICK = TYPE_SOUND + SCENE_COMMON + STAGE_NONE + 1,
	//mainmenu
	SOUND_MENUAUDIO = TYPE_SOUND + SCENE_MAINMENU + STAGE_NONE + 1,
	//gameplay - none
	SOUND_PALYAUDIO = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_NONE + 1,
	//gameplay - gameplay
	SOUND_BLOCKDROP = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_GAMEPLAY + 1,
	//gameplay - gameover
	SOUND_GAMEOVER = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_GAMEOVER + 1,
	//gameresult
	SOUND_RESULTAUDIO = TYPE_SOUND + SCENE_GAMERESULT + STAGE_NONE + 1,
};


#endif /* RESOURCESID_H_ */

